// SPDX-License-Identifier: Apache-2.0

// Package asmai holds what the asmai executable carries from the repository
// root: AsmAI's LICENSE and the generated third-party notices.
package asmai

import _ "embed"

// License is AsmAI's LICENSE.
//
//go:embed LICENSE
var License []byte

// ThirdPartyNotices is THIRD_PARTY_NOTICES, generated by
// `go run ./internal/cmd/gen-notices` from the Go distribution's LICENSE and
// every Go module compiled into asmai.
//
//go:embed THIRD_PARTY_NOTICES
var ThirdPartyNotices []byte
